VERSION: 2
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_botnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]] 
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: &num_classes 80
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
  BOTNET:
    FMAP_SIZE: 64
    DIM_OUT: 2048
    PROJ_FACTOR: 4
    DOWNSAMPLE: True
    HEADS: 4
    DIM_HEAD: 256
    USE_RELATIVE_POS_EMB: True
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  AMP:
    ENABLED: True
  IMS_PER_BATCH: 16
  BASE_LR: 0.002
  STEPS: (30000, 60000)
  MAX_ITER: 200000
  NESTEROV: False
  WARMUP_ITERS: 1000
  CHECKPOINT_PERIOD: 5000
  WEIGHT_DECAY: 0.00004
INPUT:
  MASK_FORMAT: "bitmask"
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  # MIN_SIZE_TRAIN: (1024, )

